#!/usr/bin/env python3
"""
Build visualizer/data.js from aggregated Political Compass results.
"""

from __future__ import annotations

import json
from pathlib import Path


VISUALIZER_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = VISUALIZER_ROOT.parent
OUTPUT_PATH = VISUALIZER_ROOT / "data.js"

AGGREGATED_RESULTS_CANDIDATES = (
    REPO_ROOT / "data" / "Aggregated Results",
    REPO_ROOT / "ai-deology" / "results" / "political_compass" / "Aggregated Results",
    REPO_ROOT / "ai-deology" / "results" / "Aggregated Results",
)


def resolve_aggregated_results_dir() -> Path:
    for candidate in AGGREGATED_RESULTS_CANDIDATES:
        if candidate.exists():
            return candidate

    searched = "\n".join(f"  - {path}" for path in AGGREGATED_RESULTS_CANDIDATES)
    raise FileNotFoundError(
        "Could not find an aggregated results directory. Checked:\n"
        f"{searched}"
    )


def sanitize_condition_payload(payload: dict, pc_file: Path) -> dict:
    sanitized = dict(payload)
    raw_source = pc_file.with_name(pc_file.name.replace("_pc.json", ".json"))

    if raw_source.exists():
        sanitized["source_file"] = raw_source.relative_to(REPO_ROOT).as_posix()
    else:
        sanitized["source_file"] = pc_file.relative_to(REPO_ROOT).as_posix()

    return sanitized


def build_dashboard_data(data_dir: Path) -> dict:
    experiment_data: dict[str, dict[str, dict]] = {}

    for model_folder in sorted(data_dir.iterdir()):
        if not model_folder.is_dir():
            continue

        folder_name = model_folder.name
        experiment_data[folder_name] = {}

        for json_file in sorted(model_folder.glob("*_pc.json")):
            filename = json_file.stem
            condition = filename.split("_")[0]

            try:
                with json_file.open("r", encoding="utf-8") as handle:
                    payload = json.load(handle)
                experiment_data[folder_name][condition] = sanitize_condition_payload(payload, json_file)
                print(f"Loaded PC data: {folder_name}/{condition}")
            except Exception as exc:
                print(f"Error loading {json_file}: {exc}")

    return {model: conditions for model, conditions in experiment_data.items() if conditions}


def main() -> None:
    data_dir = resolve_aggregated_results_dir()
    experiment_data = build_dashboard_data(data_dir)

    js_content = "// Auto-generated data file - do not edit manually\n"
    js_content += "// Generated by visualizer/scripts/build_data.py\n"
    js_content += "// Economic axis: Left (-10) to Right (+10)\n"
    js_content += "// Social axis: Libertarian (-10) to Authoritarian (+10)\n\n"
    js_content += "window.experimentData = "
    js_content += json.dumps(experiment_data, indent=2, ensure_ascii=False)
    js_content += ";\n"

    OUTPUT_PATH.write_text(js_content, encoding="utf-8")

    print(
        f"\n✓ Generated {OUTPUT_PATH.name} with {len(experiment_data)} "
        "model folders (Political Compass format)"
    )
    print(f"Using aggregated results from: {data_dir}")

    for folder, conditions in experiment_data.items():
        print(f"  {folder}: {list(conditions.keys())}")


if __name__ == "__main__":
    main()
